### ISSUE TITLE
Prepare TFRecords of the dataset

### ISSUE THREAD

**Issue by sayakpaul** [deep-diver/segformer-in-ml-pipeline#1]
Dataset shown in this blog: https://huggingface.co/blog/fine-tune-segformer. 

@deep-diver FYI.

**Comment by deep-diver** [comment]
so, get the dataset, and convert it into TFRecord format?

**Comment by sayakpaul** [comment]
Yes. Do you have any other dataset in mind?

**Comment by deep-diver** [comment]
nope. I was just wondering if there is already prepared dataset for Semantic Segmentation task. It looks like There are few in TensorFlow Datasets, but they are usually huge. 

So, I think your idea is good, and I can learn how to construct TFRecord for Semantic Segmentation along the way!

**Comment by sayakpaul** [comment]
Sweet!
